version: '3'

env:
  DATABASE_URL: "postgres://root:@localhost:5432/boiler?sslmode=disable"

tasks:
  run:
    cmds:
      - go run app.go

  migrate:
    cmds:
      - migrate -source file://resources/sql -database {{.DATABASE_URL}} up
  migrate-drop:
    cmds:
      - migrate -database {{.DATABASE_URL}} -source file://resources/sql drop
  migrate-create:
    cmds: 
      - migrate create -ext sql -dir resources/sql "{{.FILE_NAME}}"
    requires:
      vars: [FILE_NAME]
        
  generate-secret:
    cmds:
      - ssh-keygen -t rsa -P "" -b 4096 -m PEM -f resources/secret/jwtRS256.key 
      - ssh-keygen -e -m PEM -f resources/secret/jwtRS256.key > resources/secret/jwtRS256.key.pub

  build-file:
    cmds:
      - statik -f -m -src=resources -dest=lib/ -p files