import FullLayout from "../src/layouts/FullLayout";
import Head from "next/head";
import NextNProgress from "nextjs-progressbar";
import "../styles/style.scss";
import "../styles/printlayout.css"

function MyApp({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => <FullLayout>{page}</FullLayout>)
  return (
    <>
      <Head>
        <title>Penala Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextNProgress color="#c8e1cc" height={5} />
      {getLayout(<Component {...pageProps} />)}
    </>
  );
}

export default MyApp;
